package com.github.pwittchen.varun.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import reactor.test.StepVerifier;

import static com.google.common.truth.Truth.assertThat;

class WeatherForecastServiceTest {

    private WeatherForecastService weatherForecastService;

    @BeforeEach
    void setUp() {
        weatherForecastService = new WeatherForecastService();
    }

    @Test
    void shouldParseWeatherForecast() {
        StepVerifier
                .create(weatherForecastService.getForecast(43, "gfs"))
                .assertNext(weatherForecast -> {
                    assertThat(weatherForecast).isNotEmpty();
                })
                .verifyComplete();

        /*

        weather data structure:

        {
  "spot" : {
    "id" : 43,
    "name" : "Tarifa"
  },
  "model_info" : {
    "init" : "2025-09-19 12 UTC",
    "line" : "GFS 13 km"
  },
  "generated_year_guess" : 2025,
  "rows" : [ {
    "label" : "Fri 19. 14h",
    "wspd_kn" : 20,
    "gust_kn" : 27,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 25,
    "slp_hpa" : 1021,
    "cloud_high_pct" : null,
    "cloud_mid_pct" : null,
    "cloud_low_pct" : null,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : null,
    "rh_pct" : 79
  }, {
    "label" : "Fri 19. 15h",
    "wspd_kn" : 21,
    "gust_kn" : 27,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 25,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 40,
    "cloud_mid_pct" : 14,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 76
  }, {
    "label" : "Fri 19. 16h",
    "wspd_kn" : 20,
    "gust_kn" : 26,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 25,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 34,
    "cloud_mid_pct" : 14,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 73
  }, {
    "label" : "Fri 19. 17h",
    "wspd_kn" : 19,
    "gust_kn" : 25,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 25,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 10,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Fri 19. 18h",
    "wspd_kn" : 18,
    "gust_kn" : 23,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 24,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 9,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Fri 19. 19h",
    "wspd_kn" : 17,
    "gust_kn" : 22,
    "wdir_compass" : "ENE",
    "wdir_deg" : 75,
    "temp_c" : 24,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 66,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Fri 19. 20h",
    "wspd_kn" : 16,
    "gust_kn" : 22,
    "wdir_compass" : "ENE",
    "wdir_deg" : 73,
    "temp_c" : 23,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 100,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 85
  }, {
    "label" : "Fri 19. 21h",
    "wspd_kn" : 16,
    "gust_kn" : 23,
    "wdir_compass" : "ENE",
    "wdir_deg" : 75,
    "temp_c" : 22,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 56,
    "cloud_mid_pct" : 61,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Fri 19. 22h",
    "wspd_kn" : 16,
    "gust_kn" : 23,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 21,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 10,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Fri 19. 23h",
    "wspd_kn" : 16,
    "gust_kn" : 24,
    "wdir_compass" : "ENE",
    "wdir_deg" : 76,
    "temp_c" : 22,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 26,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sat 20. 00h",
    "wspd_kn" : 16,
    "gust_kn" : 23,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 22,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 84,
    "cloud_mid_pct" : 82,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Sat 20. 01h",
    "wspd_kn" : 14,
    "gust_kn" : 22,
    "wdir_compass" : "ENE",
    "wdir_deg" : 72,
    "temp_c" : 21,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 98,
    "cloud_mid_pct" : 10,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Sat 20. 02h",
    "wspd_kn" : 16,
    "gust_kn" : 23,
    "wdir_compass" : "E",
    "wdir_deg" : 82,
    "temp_c" : 21,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 32,
    "cloud_low_pct" : 5,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 93
  }, {
    "label" : "Sat 20. 03h",
    "wspd_kn" : 15,
    "gust_kn" : 20,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 22,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 84,
    "cloud_low_pct" : 32,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sat 20. 04h",
    "wspd_kn" : 14,
    "gust_kn" : 19,
    "wdir_compass" : "ENE",
    "wdir_deg" : 73,
    "temp_c" : 21,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 39,
    "cloud_low_pct" : 5,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Sat 20. 05h",
    "wspd_kn" : 15,
    "gust_kn" : 19,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 21,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 96,
    "cloud_low_pct" : 7,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Sat 20. 06h",
    "wspd_kn" : 13,
    "gust_kn" : 18,
    "wdir_compass" : "ENE",
    "wdir_deg" : 75,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 39,
    "cloud_low_pct" : 6,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 93
  }, {
    "label" : "Sat 20. 07h",
    "wspd_kn" : 14,
    "gust_kn" : 18,
    "wdir_compass" : "ENE",
    "wdir_deg" : 73,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 74,
    "cloud_low_pct" : 4,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 93
  }, {
    "label" : "Sat 20. 08h",
    "wspd_kn" : 15,
    "gust_kn" : 20,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 21,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 61,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Sat 20. 09h",
    "wspd_kn" : 15,
    "gust_kn" : 20,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 22,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 61,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sat 20. 10h",
    "wspd_kn" : 15,
    "gust_kn" : 19,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 22,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 97,
    "cloud_mid_pct" : 90,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Sat 20. 11h",
    "wspd_kn" : 14,
    "gust_kn" : 18,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 23,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Sat 20. 12h",
    "wspd_kn" : 15,
    "gust_kn" : 19,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 24,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 3,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 81
  }, {
    "label" : "Sat 20. 13h",
    "wspd_kn" : 16,
    "gust_kn" : 19,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 24,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sat 20. 14h",
    "wspd_kn" : 16,
    "gust_kn" : 19,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 25,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 78
  }, {
    "label" : "Sat 20. 15h",
    "wspd_kn" : 15,
    "gust_kn" : 18,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 25,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 19,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Sat 20. 16h",
    "wspd_kn" : 15,
    "gust_kn" : 18,
    "wdir_compass" : "ENE",
    "wdir_deg" : 77,
    "temp_c" : 25,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 4,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Sat 20. 17h",
    "wspd_kn" : 15,
    "gust_kn" : 18,
    "wdir_compass" : "ENE",
    "wdir_deg" : 78,
    "temp_c" : 25,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 11,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Sat 20. 18h",
    "wspd_kn" : 15,
    "gust_kn" : 18,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 24,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 11,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sat 20. 19h",
    "wspd_kn" : 14,
    "gust_kn" : 16,
    "wdir_compass" : "ENE",
    "wdir_deg" : 74,
    "temp_c" : 23,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 16,
    "cloud_mid_pct" : 10,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Sat 20. 20h",
    "wspd_kn" : 12,
    "gust_kn" : 15,
    "wdir_compass" : "ENE",
    "wdir_deg" : 74,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 37,
    "cloud_mid_pct" : 46,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Sat 20. 21h",
    "wspd_kn" : 11,
    "gust_kn" : 14,
    "wdir_compass" : "ENE",
    "wdir_deg" : 73,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 10,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Sat 20. 22h",
    "wspd_kn" : 10,
    "gust_kn" : 12,
    "wdir_compass" : "ENE",
    "wdir_deg" : 71,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 25,
    "cloud_mid_pct" : 83,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sat 20. 23h",
    "wspd_kn" : 9,
    "gust_kn" : 10,
    "wdir_compass" : "ENE",
    "wdir_deg" : 68,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 84,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 00h",
    "wspd_kn" : 8,
    "gust_kn" : 8,
    "wdir_compass" : "ENE",
    "wdir_deg" : 60,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 71,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 01h",
    "wspd_kn" : 6,
    "gust_kn" : 6,
    "wdir_compass" : "ENE",
    "wdir_deg" : 57,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 89,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 02h",
    "wspd_kn" : 5,
    "gust_kn" : 5,
    "wdir_compass" : "ENE",
    "wdir_deg" : 62,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 84,
    "cloud_low_pct" : 3,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 03h",
    "wspd_kn" : 5,
    "gust_kn" : 5,
    "wdir_compass" : "ENE",
    "wdir_deg" : 67,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 94,
    "cloud_low_pct" : 3,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 04h",
    "wspd_kn" : 4,
    "gust_kn" : 4,
    "wdir_compass" : "E",
    "wdir_deg" : 88,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 79,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 05h",
    "wspd_kn" : 4,
    "gust_kn" : 3,
    "wdir_compass" : "SE",
    "wdir_deg" : 125,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 22,
    "cloud_mid_pct" : 98,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 94
  }, {
    "label" : "Sun 21. 06h",
    "wspd_kn" : 2,
    "gust_kn" : 3,
    "wdir_compass" : "S",
    "wdir_deg" : 182,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 86,
    "cloud_mid_pct" : 98,
    "cloud_low_pct" : 8,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 93
  }, {
    "label" : "Sun 21. 07h",
    "wspd_kn" : 4,
    "gust_kn" : 4,
    "wdir_compass" : "SW",
    "wdir_deg" : 228,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 98,
    "cloud_mid_pct" : 95,
    "cloud_low_pct" : 67,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Sun 21. 08h",
    "wspd_kn" : 4,
    "gust_kn" : 4,
    "wdir_compass" : "WSW",
    "wdir_deg" : 257,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 11,
    "cloud_mid_pct" : 75,
    "cloud_low_pct" : 41,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Sun 21. 09h",
    "wspd_kn" : 4,
    "gust_kn" : 5,
    "wdir_compass" : "W",
    "wdir_deg" : 265,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 14,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 13,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Sun 21. 10h",
    "wspd_kn" : 6,
    "gust_kn" : 8,
    "wdir_compass" : "WSW",
    "wdir_deg" : 250,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 66,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Sun 21. 11h",
    "wspd_kn" : 8,
    "gust_kn" : 10,
    "wdir_compass" : "WSW",
    "wdir_deg" : 258,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 13,
    "cloud_mid_pct" : 4,
    "cloud_low_pct" : 2,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 78
  }, {
    "label" : "Sun 21. 12h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 264,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 7,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 72
  }, {
    "label" : "Sun 21. 13h",
    "wspd_kn" : 11,
    "gust_kn" : 12,
    "wdir_compass" : "WSW",
    "wdir_deg" : 257,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 10,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 66
  }, {
    "label" : "Sun 21. 14h",
    "wspd_kn" : 11,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 266,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 19,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 62
  }, {
    "label" : "Sun 21. 15h",
    "wspd_kn" : 11,
    "gust_kn" : 15,
    "wdir_compass" : "W",
    "wdir_deg" : 274,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 85,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 59
  }, {
    "label" : "Sun 21. 16h",
    "wspd_kn" : 11,
    "gust_kn" : 15,
    "wdir_compass" : "W",
    "wdir_deg" : 275,
    "temp_c" : 22,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 84,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 57
  }, {
    "label" : "Sun 21. 17h",
    "wspd_kn" : 11,
    "gust_kn" : 16,
    "wdir_compass" : "W",
    "wdir_deg" : 273,
    "temp_c" : 23,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 89,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 55
  }, {
    "label" : "Sun 21. 18h",
    "wspd_kn" : 10,
    "gust_kn" : 15,
    "wdir_compass" : "W",
    "wdir_deg" : 270,
    "temp_c" : 23,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 54
  }, {
    "label" : "Sun 21. 19h",
    "wspd_kn" : 10,
    "gust_kn" : 15,
    "wdir_compass" : "W",
    "wdir_deg" : 272,
    "temp_c" : 22,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 55
  }, {
    "label" : "Sun 21. 20h",
    "wspd_kn" : 10,
    "gust_kn" : 15,
    "wdir_compass" : "W",
    "wdir_deg" : 274,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 62
  }, {
    "label" : "Sun 21. 21h",
    "wspd_kn" : 9,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 275,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 68
  }, {
    "label" : "Sun 21. 22h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "W",
    "wdir_deg" : 268,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 70
  }, {
    "label" : "Sun 21. 23h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 260,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 3,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 72
  }, {
    "label" : "Mon 22. 00h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "WSW",
    "wdir_deg" : 245,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Mon 22. 01h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WSW",
    "wdir_deg" : 239,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 4,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 75
  }, {
    "label" : "Mon 22. 02h",
    "wspd_kn" : 9,
    "gust_kn" : 13,
    "wdir_compass" : "SW",
    "wdir_deg" : 234,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 76
  }, {
    "label" : "Mon 22. 03h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WSW",
    "wdir_deg" : 244,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Mon 22. 04h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WSW",
    "wdir_deg" : 252,
    "temp_c" : 20,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 71
  }, {
    "label" : "Mon 22. 05h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WSW",
    "wdir_deg" : 254,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 67
  }, {
    "label" : "Mon 22. 06h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "W",
    "wdir_deg" : 260,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 63
  }, {
    "label" : "Mon 22. 07h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "W",
    "wdir_deg" : 260,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 59
  }, {
    "label" : "Mon 22. 08h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 262,
    "temp_c" : 18,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 56
  }, {
    "label" : "Mon 22. 09h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 261,
    "temp_c" : 19,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 54
  }, {
    "label" : "Mon 22. 10h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "WSW",
    "wdir_deg" : 257,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 52
  }, {
    "label" : "Mon 22. 11h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 262,
    "temp_c" : 20,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 4,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 52
  }, {
    "label" : "Mon 22. 12h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 269,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 6,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 51
  }, {
    "label" : "Mon 22. 13h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "W",
    "wdir_deg" : 275,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 6,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 53
  }, {
    "label" : "Mon 22. 14h",
    "wspd_kn" : 10,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 276,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 7,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 54
  }, {
    "label" : "Mon 22. 15h",
    "wspd_kn" : 10,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 280,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 69,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 55
  }, {
    "label" : "Mon 22. 16h",
    "wspd_kn" : 10,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 280,
    "temp_c" : 21,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 56
  }, {
    "label" : "Mon 22. 17h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "W",
    "wdir_deg" : 281,
    "temp_c" : 21,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 56
  }, {
    "label" : "Mon 22. 18h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 21,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 58
  }, {
    "label" : "Mon 22. 19h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 284,
    "temp_c" : 20,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 59
  }, {
    "label" : "Mon 22. 20h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 20,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : null,
    "apcp_mm_1h" : 0,
    "rh_pct" : 63
  }, {
    "label" : "Mon 22. 23h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "W",
    "wdir_deg" : 273,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 64
  }, {
    "label" : "Tue 23. 02h",
    "wspd_kn" : 6,
    "gust_kn" : 9,
    "wdir_compass" : "W",
    "wdir_deg" : 264,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 99,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 70
  }, {
    "label" : "Tue 23. 05h",
    "wspd_kn" : 5,
    "gust_kn" : 7,
    "wdir_compass" : "W",
    "wdir_deg" : 259,
    "temp_c" : 18,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 90,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 73
  }, {
    "label" : "Tue 23. 08h",
    "wspd_kn" : 5,
    "gust_kn" : 7,
    "wdir_compass" : "SW",
    "wdir_deg" : 224,
    "temp_c" : 18,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 72
  }, {
    "label" : "Tue 23. 11h",
    "wspd_kn" : 6,
    "gust_kn" : 7,
    "wdir_compass" : "WSW",
    "wdir_deg" : 239,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 90,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 59
  }, {
    "label" : "Tue 23. 14h",
    "wspd_kn" : 8,
    "gust_kn" : 7,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 22,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 3,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 57
  }, {
    "label" : "Tue 23. 17h",
    "wspd_kn" : 6,
    "gust_kn" : 6,
    "wdir_compass" : "W",
    "wdir_deg" : 271,
    "temp_c" : 22,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 58
  }, {
    "label" : "Tue 23. 20h",
    "wspd_kn" : 5,
    "gust_kn" : 6,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 20,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 66
  }, {
    "label" : "Tue 23. 23h",
    "wspd_kn" : 4,
    "gust_kn" : 4,
    "wdir_compass" : "E",
    "wdir_deg" : 81,
    "temp_c" : 19,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 16,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 66
  }, {
    "label" : "Wed 24. 02h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "ENE",
    "wdir_deg" : 65,
    "temp_c" : 19,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 35,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 78
  }, {
    "label" : "Wed 24. 05h",
    "wspd_kn" : 11,
    "gust_kn" : 19,
    "wdir_compass" : "E",
    "wdir_deg" : 81,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Wed 24. 08h",
    "wspd_kn" : 15,
    "gust_kn" : 25,
    "wdir_compass" : "E",
    "wdir_deg" : 84,
    "temp_c" : 21,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 31,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Wed 24. 11h",
    "wspd_kn" : 20,
    "gust_kn" : 27,
    "wdir_compass" : "E",
    "wdir_deg" : 92,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 18,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Wed 24. 14h",
    "wspd_kn" : 22,
    "gust_kn" : 28,
    "wdir_compass" : "E",
    "wdir_deg" : 90,
    "temp_c" : 23,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 69,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Wed 24. 17h",
    "wspd_kn" : 21,
    "gust_kn" : 27,
    "wdir_compass" : "E",
    "wdir_deg" : 88,
    "temp_c" : 23,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 30,
    "cloud_mid_pct" : 23,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Wed 24. 20h",
    "wspd_kn" : 18,
    "gust_kn" : 28,
    "wdir_compass" : "E",
    "wdir_deg" : 83,
    "temp_c" : 21,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 99,
    "cloud_mid_pct" : 78,
    "cloud_low_pct" : 4,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Wed 24. 23h",
    "wspd_kn" : 19,
    "gust_kn" : 29,
    "wdir_compass" : "E",
    "wdir_deg" : 88,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 58,
    "cloud_mid_pct" : 95,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Th",
    "wspd_kn" : 19,
    "gust_kn" : 29,
    "wdir_compass" : "E",
    "wdir_deg" : 92,
    "temp_c" : 21,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 95,
    "cloud_mid_pct" : 88,
    "cloud_low_pct" : 3,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Th",
    "wspd_kn" : 19,
    "gust_kn" : 29,
    "wdir_compass" : "E",
    "wdir_deg" : 92,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 92,
    "cloud_mid_pct" : 67,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Th",
    "wspd_kn" : 14,
    "gust_kn" : 24,
    "wdir_compass" : "E",
    "wdir_deg" : 99,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 87,
    "cloud_mid_pct" : 6,
    "cloud_low_pct" : 2,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 86
  }, {
    "label" : "Th",
    "wspd_kn" : 11,
    "gust_kn" : 16,
    "wdir_compass" : "ESE",
    "wdir_deg" : 114,
    "temp_c" : 22,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 1,
    "cloud_low_pct" : 18,
    "apcp_mm_3h" : 3,
    "apcp_mm_1h" : 1,
    "rh_pct" : 81
  }, {
    "label" : "Th",
    "wspd_kn" : 3,
    "gust_kn" : 4,
    "wdir_compass" : "S",
    "wdir_deg" : 182,
    "temp_c" : 19,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 32,
    "cloud_mid_pct" : 3,
    "cloud_low_pct" : 100,
    "apcp_mm_3h" : 9,
    "apcp_mm_1h" : 3,
    "rh_pct" : 90
  }, {
    "label" : "Th",
    "wspd_kn" : 0,
    "gust_kn" : 3,
    "wdir_compass" : "NE",
    "wdir_deg" : 47,
    "temp_c" : 18,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 100,
    "apcp_mm_3h" : 5,
    "apcp_mm_1h" : 2,
    "rh_pct" : 95
  }, {
    "label" : "Th",
    "wspd_kn" : 3,
    "gust_kn" : 5,
    "wdir_compass" : "NNE",
    "wdir_deg" : 33,
    "temp_c" : 20,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 100,
    "apcp_mm_3h" : 3,
    "apcp_mm_1h" : 1,
    "rh_pct" : 94
  }, {
    "label" : "Th",
    "wspd_kn" : 2,
    "gust_kn" : 3,
    "wdir_compass" : "NNE",
    "wdir_deg" : 30,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 100,
    "apcp_mm_3h" : 1,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Fri 26. 02h",
    "wspd_kn" : 1,
    "gust_kn" : 2,
    "wdir_compass" : "NNW",
    "wdir_deg" : 331,
    "temp_c" : 19,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 94,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Fri 26. 05h",
    "wspd_kn" : 6,
    "gust_kn" : 8,
    "wdir_compass" : "WSW",
    "wdir_deg" : 253,
    "temp_c" : 19,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 99,
    "apcp_mm_3h" : 1,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Fri 26. 08h",
    "wspd_kn" : 8,
    "gust_kn" : 13,
    "wdir_compass" : "WSW",
    "wdir_deg" : 255,
    "temp_c" : 19,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 1,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 43,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Fri 26. 11h",
    "wspd_kn" : 11,
    "gust_kn" : 13,
    "wdir_compass" : "WSW",
    "wdir_deg" : 237,
    "temp_c" : 20,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 20,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 75
  }, {
    "label" : "Fri 26. 14h",
    "wspd_kn" : 13,
    "gust_kn" : 15,
    "wdir_compass" : "WSW",
    "wdir_deg" : 247,
    "temp_c" : 21,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 23,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 69
  }, {
    "label" : "Fri 26. 17h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 278,
    "temp_c" : 21,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 3,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Fri 26. 20h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 288,
    "temp_c" : 20,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 78,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 75
  }, {
    "label" : "Fri 26. 23h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "W",
    "wdir_deg" : 276,
    "temp_c" : 19,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 91,
    "cloud_mid_pct" : 4,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sat 27. 02h",
    "wspd_kn" : 6,
    "gust_kn" : 9,
    "wdir_compass" : "W",
    "wdir_deg" : 278,
    "temp_c" : 19,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 24,
    "cloud_mid_pct" : 15,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 83
  }, {
    "label" : "Sat 27. 05h",
    "wspd_kn" : 7,
    "gust_kn" : 9,
    "wdir_compass" : "WSW",
    "wdir_deg" : 258,
    "temp_c" : 19,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 3,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Sat 27. 08h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "SW",
    "wdir_deg" : 236,
    "temp_c" : 19,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Sat 27. 11h",
    "wspd_kn" : 8,
    "gust_kn" : 10,
    "wdir_compass" : "WSW",
    "wdir_deg" : 246,
    "temp_c" : 20,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 17,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 28,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Sat 27. 14h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 269,
    "temp_c" : 21,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 87,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 7,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Sat 27. 17h",
    "wspd_kn" : 9,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 274,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 49,
    "cloud_mid_pct" : 7,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 68
  }, {
    "label" : "Sat 27. 20h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 276,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 4,
    "cloud_mid_pct" : 5,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 68
  }, {
    "label" : "Sat 27. 23h",
    "wspd_kn" : 7,
    "gust_kn" : 9,
    "wdir_compass" : "W",
    "wdir_deg" : 274,
    "temp_c" : 19,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 75
  }, {
    "label" : "Sun 28. 02h",
    "wspd_kn" : 7,
    "gust_kn" : 9,
    "wdir_compass" : "W",
    "wdir_deg" : 266,
    "temp_c" : 19,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 21,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Sun 28. 05h",
    "wspd_kn" : 6,
    "gust_kn" : 9,
    "wdir_compass" : "WSW",
    "wdir_deg" : 241,
    "temp_c" : 19,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 66,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sun 28. 08h",
    "wspd_kn" : 6,
    "gust_kn" : 10,
    "wdir_compass" : "WSW",
    "wdir_deg" : 239,
    "temp_c" : 19,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 17,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 83
  }, {
    "label" : "Sun 28. 11h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "WSW",
    "wdir_deg" : 253,
    "temp_c" : 20,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 62,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Sun 28. 14h",
    "wspd_kn" : 8,
    "gust_kn" : 10,
    "wdir_compass" : "W",
    "wdir_deg" : 277,
    "temp_c" : 21,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 36,
    "cloud_mid_pct" : 9,
    "cloud_low_pct" : 48,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 83
  }, {
    "label" : "Sun 28. 17h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WNW",
    "wdir_deg" : 283,
    "temp_c" : 22,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 46,
    "cloud_mid_pct" : 15,
    "cloud_low_pct" : 7,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sun 28. 20h",
    "wspd_kn" : 7,
    "gust_kn" : 9,
    "wdir_compass" : "WNW",
    "wdir_deg" : 285,
    "temp_c" : 21,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 97,
    "cloud_mid_pct" : 57,
    "cloud_low_pct" : 5,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Sun 28. 23h",
    "wspd_kn" : 6,
    "gust_kn" : 7,
    "wdir_compass" : "WNW",
    "wdir_deg" : 288,
    "temp_c" : 20,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 100,
    "cloud_mid_pct" : 85,
    "cloud_low_pct" : 1,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Mon 29. 02h",
    "wspd_kn" : 6,
    "gust_kn" : 8,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 20,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 35,
    "cloud_mid_pct" : 76,
    "cloud_low_pct" : 2,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 85
  }, {
    "label" : "Mon 29. 05h",
    "wspd_kn" : 6,
    "gust_kn" : 7,
    "wdir_compass" : "W",
    "wdir_deg" : 281,
    "temp_c" : 19,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 38,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Mon 29. 08h",
    "wspd_kn" : 5,
    "gust_kn" : 6,
    "wdir_compass" : "W",
    "wdir_deg" : 270,
    "temp_c" : 19,
    "slp_hpa" : 1013,
    "cloud_high_pct" : 1,
    "cloud_mid_pct" : 86,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Mon 29. 11h",
    "wspd_kn" : 6,
    "gust_kn" : 7,
    "wdir_compass" : "W",
    "wdir_deg" : 262,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 17,
    "cloud_mid_pct" : 80,
    "cloud_low_pct" : 2,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Mon 29. 14h",
    "wspd_kn" : 8,
    "gust_kn" : 10,
    "wdir_compass" : "WNW",
    "wdir_deg" : 291,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 79,
    "cloud_mid_pct" : 97,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Mon 29. 17h",
    "wspd_kn" : 9,
    "gust_kn" : 12,
    "wdir_compass" : "WNW",
    "wdir_deg" : 290,
    "temp_c" : 22,
    "slp_hpa" : 1014,
    "cloud_high_pct" : 38,
    "cloud_mid_pct" : 91,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Mon 29. 20h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 282,
    "temp_c" : 21,
    "slp_hpa" : 1015,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 85,
    "cloud_low_pct" : 11,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 86
  }, {
    "label" : "Mon 29. 23h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "WNW",
    "wdir_deg" : 289,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 24,
    "cloud_low_pct" : 47,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 93
  }, {
    "label" : "Tue 30. 02h",
    "wspd_kn" : 7,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 288,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 32,
    "cloud_mid_pct" : 27,
    "cloud_low_pct" : 6,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Tue 30. 05h",
    "wspd_kn" : 8,
    "gust_kn" : 11,
    "wdir_compass" : "NW",
    "wdir_deg" : 310,
    "temp_c" : 19,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 37,
    "cloud_mid_pct" : 8,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 81
  }, {
    "label" : "Tue 30. 08h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "NW",
    "wdir_deg" : 307,
    "temp_c" : 17,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 73
  }, {
    "label" : "Tue 30. 11h",
    "wspd_kn" : 9,
    "gust_kn" : 11,
    "wdir_compass" : "WNW",
    "wdir_deg" : 297,
    "temp_c" : 20,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 64
  }, {
    "label" : "Tue 30. 14h",
    "wspd_kn" : 10,
    "gust_kn" : 11,
    "wdir_compass" : "W",
    "wdir_deg" : 264,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 2,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 60
  }, {
    "label" : "Tue 30. 17h",
    "wspd_kn" : 10,
    "gust_kn" : 13,
    "wdir_compass" : "W",
    "wdir_deg" : 275,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 72,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 62
  }, {
    "label" : "Tue 30. 20h",
    "wspd_kn" : 8,
    "gust_kn" : 14,
    "wdir_compass" : "W",
    "wdir_deg" : 273,
    "temp_c" : 19,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 18,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 72
  }, {
    "label" : "Tue 30. 23h",
    "wspd_kn" : 9,
    "gust_kn" : 14,
    "wdir_compass" : "WNW",
    "wdir_deg" : 296,
    "temp_c" : 19,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 7,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 74
  }, {
    "label" : "Wed 1. 02h",
    "wspd_kn" : 7,
    "gust_kn" : 10,
    "wdir_compass" : "W",
    "wdir_deg" : 265,
    "temp_c" : 18,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 25,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 81
  }, {
    "label" : "Wed 1. 05h",
    "wspd_kn" : 7,
    "gust_kn" : 9,
    "wdir_compass" : "WSW",
    "wdir_deg" : 243,
    "temp_c" : 18,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 97,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Wed 1. 08h",
    "wspd_kn" : 6,
    "gust_kn" : 8,
    "wdir_compass" : "WSW",
    "wdir_deg" : 255,
    "temp_c" : 18,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 93,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Wed 1. 11h",
    "wspd_kn" : 6,
    "gust_kn" : 7,
    "wdir_compass" : "W",
    "wdir_deg" : 265,
    "temp_c" : 20,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 50,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 61
  }, {
    "label" : "Wed 1. 14h",
    "wspd_kn" : 7,
    "gust_kn" : 6,
    "wdir_compass" : "SW",
    "wdir_deg" : 227,
    "temp_c" : 22,
    "slp_hpa" : 1020,
    "cloud_high_pct" : 12,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 55
  }, {
    "label" : "Wed 1. 17h",
    "wspd_kn" : 5,
    "gust_kn" : 5,
    "wdir_compass" : "SW",
    "wdir_deg" : 220,
    "temp_c" : 22,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 19,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 62
  }, {
    "label" : "Wed 1. 20h",
    "wspd_kn" : 4,
    "gust_kn" : 4,
    "wdir_compass" : "ESE",
    "wdir_deg" : 102,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 62,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 64
  }, {
    "label" : "Wed 1. 23h",
    "wspd_kn" : 9,
    "gust_kn" : 10,
    "wdir_compass" : "ENE",
    "wdir_deg" : 59,
    "temp_c" : 20,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 16,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 77
  }, {
    "label" : "Th",
    "wspd_kn" : 11,
    "gust_kn" : 16,
    "wdir_compass" : "ENE",
    "wdir_deg" : 70,
    "temp_c" : 19,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Th",
    "wspd_kn" : 13,
    "gust_kn" : 22,
    "wdir_compass" : "ENE",
    "wdir_deg" : 76,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 14,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 3,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Th",
    "wspd_kn" : 15,
    "gust_kn" : 24,
    "wdir_compass" : "ENE",
    "wdir_deg" : 74,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 60,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 92
  }, {
    "label" : "Th",
    "wspd_kn" : 21,
    "gust_kn" : 29,
    "wdir_compass" : "E",
    "wdir_deg" : 84,
    "temp_c" : 22,
    "slp_hpa" : 1019,
    "cloud_high_pct" : 49,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 3,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 85
  }, {
    "label" : "Th",
    "wspd_kn" : 25,
    "gust_kn" : 31,
    "wdir_compass" : "E",
    "wdir_deg" : 89,
    "temp_c" : 23,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 11,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 81
  }, {
    "label" : "Th",
    "wspd_kn" : 25,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 87,
    "temp_c" : 22,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 6,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 83
  }, {
    "label" : "Th",
    "wspd_kn" : 20,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 80,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 5,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Th",
    "wspd_kn" : 19,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 1,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 86
  }, {
    "label" : "Fri 3. 02h",
    "wspd_kn" : 20,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 80,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 63,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Fri 3. 05h",
    "wspd_kn" : 21,
    "gust_kn" : 31,
    "wdir_compass" : "E",
    "wdir_deg" : 81,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 41,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Fri 3. 08h",
    "wspd_kn" : 23,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 84,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 98,
    "cloud_mid_pct" : 73,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Fri 3. 11h",
    "wspd_kn" : 24,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 89,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 53,
    "cloud_mid_pct" : 1,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 82
  }, {
    "label" : "Fri 3. 14h",
    "wspd_kn" : 25,
    "gust_kn" : 31,
    "wdir_compass" : "E",
    "wdir_deg" : 89,
    "temp_c" : 22,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 57,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 76
  }, {
    "label" : "Fri 3. 17h",
    "wspd_kn" : 24,
    "gust_kn" : 30,
    "wdir_compass" : "E",
    "wdir_deg" : 84,
    "temp_c" : 22,
    "slp_hpa" : 1016,
    "cloud_high_pct" : 3,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 79
  }, {
    "label" : "Fri 3. 20h",
    "wspd_kn" : 21,
    "gust_kn" : 31,
    "wdir_compass" : "E",
    "wdir_deg" : 79,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 4,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Fri 3. 23h",
    "wspd_kn" : 23,
    "gust_kn" : 33,
    "wdir_compass" : "E",
    "wdir_deg" : 81,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 6,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Sat 4. 02h",
    "wspd_kn" : 22,
    "gust_kn" : 33,
    "wdir_compass" : "E",
    "wdir_deg" : 82,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 8,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 2,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Sat 4. 05h",
    "wspd_kn" : 25,
    "gust_kn" : 35,
    "wdir_compass" : "E",
    "wdir_deg" : 83,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 52,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 1,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 89
  }, {
    "label" : "Sat 4. 08h",
    "wspd_kn" : 26,
    "gust_kn" : 35,
    "wdir_compass" : "E",
    "wdir_deg" : 86,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 93,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 88
  }, {
    "label" : "Sat 4. 11h",
    "wspd_kn" : 28,
    "gust_kn" : 36,
    "wdir_compass" : "E",
    "wdir_deg" : 88,
    "temp_c" : 21,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 41,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 83
  }, {
    "label" : "Sat 4. 14h",
    "wspd_kn" : 29,
    "gust_kn" : 37,
    "wdir_compass" : "E",
    "wdir_deg" : 88,
    "temp_c" : 22,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 8,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sat 4. 17h",
    "wspd_kn" : 29,
    "gust_kn" : 37,
    "wdir_compass" : "E",
    "wdir_deg" : 83,
    "temp_c" : 22,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 1,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  }, {
    "label" : "Sat 4. 20h",
    "wspd_kn" : 25,
    "gust_kn" : 36,
    "wdir_compass" : "E",
    "wdir_deg" : 85,
    "temp_c" : 21,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 87
  }, {
    "label" : "Sat 4. 23h",
    "wspd_kn" : 22,
    "gust_kn" : 34,
    "wdir_compass" : "E",
    "wdir_deg" : 82,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 2,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 90
  }, {
    "label" : "Sun 5. 02h",
    "wspd_kn" : 24,
    "gust_kn" : 35,
    "wdir_compass" : "E",
    "wdir_deg" : 82,
    "temp_c" : 20,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 33,
    "cloud_mid_pct" : 1,
    "cloud_low_pct" : 9,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sun 5. 05h",
    "wspd_kn" : 23,
    "gust_kn" : 34,
    "wdir_compass" : "E",
    "wdir_deg" : 80,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 0,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 12,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sun 5. 08h",
    "wspd_kn" : 22,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 80,
    "temp_c" : 20,
    "slp_hpa" : 1017,
    "cloud_high_pct" : 1,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 24,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 91
  }, {
    "label" : "Sun 5. 11h",
    "wspd_kn" : 23,
    "gust_kn" : 32,
    "wdir_compass" : "E",
    "wdir_deg" : 81,
    "temp_c" : 22,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 2,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 4,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 84
  }, {
    "label" : "Sun 5. 14h",
    "wspd_kn" : 25,
    "gust_kn" : 31,
    "wdir_compass" : "E",
    "wdir_deg" : 84,
    "temp_c" : 22,
    "slp_hpa" : 1018,
    "cloud_high_pct" : 30,
    "cloud_mid_pct" : 0,
    "cloud_low_pct" : 0,
    "apcp_mm_3h" : 0,
    "apcp_mm_1h" : 0,
    "rh_pct" : 80
  } ]
}

         */
    }
}