// Translations configuration
const translations = {
    en: {
        // Page title
        pageTitle: "VARUN.SURF",

        // Header
        searchPlaceholder: "Search spots...",
        allCountries: "All",
        spotsCount: "spots",

        // Tooltips
        themeToggleTooltip: "Toggle theme",
        favoritesToggleTooltip: "View favorites",
        infoToggleTooltip: "About VARUN.SURF",
        infoButtonLabel: "Info",
        kiteSizeToggleTooltip: "Kite/Board Size Calculator",
        columnToggleTooltip: "Toggle 2/3 columns",
        languageToggleTooltip: "Change language",

        // Weather table headers
        dateHeader: "Date",
        windHeader: "Wind",
        gustsHeader: "Gusts",
        directionHeader: "Direction",
        tempHeader: "Temp",
        rainHeader: "Rain",
        waveHeader: "Wave",
        nowLabel: "NOW",

        // Footer
        footerDisclaimer: "weather forecast and real-time wind conditions dashboard for kitesurfers",

        // Days of week (short forms as they appear in forecast)
        dayToday: "Today",
        dayTomorrow: "Tomorrow",
        dayDay3: "Day 3",
        dayDay4: "Day 4",
        dayDay5: "Day 5",

        // Language code
        langCode: "EN",

        // Error handling
        error: "Error",
        invalidSpotId: "Invalid or missing spot identifier.",
        spotNotFound: "We couldn't find this spot. Double-check the link or pick another location.",
        errorLoadingSpot: "Unable to load spot information. Please try again shortly.",

        // Error messages
        errorNoSpotsTitle: "No Spots Found",
        errorNoSpotsDescription: "No kitesurfing spots found for the selected filter.",
        errorNoSpotsSearchDescription: "No spots found matching",
        errorTryAdjusting: "Try adjusting your search or selecting \"All\" countries.",
        errorLoadDataTitle: "Failed to Load Weather Data",
        errorLoadDataDescription: "Unable to fetch the latest weather information from the server.",
        errorDataNotFoundTitle: "Data Source Not Found",
        errorDataNotFoundDescription: "The weather data endpoint is not available. Please check if the server is running.",
        errorServerTitle: "Server Error",
        errorServerDescription: "The weather service is experiencing technical difficulties. Please try again later.",
        errorConnectionTitle: "Connection Error",
        errorConnectionDescription: "Unable to connect to the weather service. Please check your internet connection and ensure the server is running.",
        errorDataFormatTitle: "Data Format Error",
        errorDataFormatDescription: "The weather data received is corrupted or in an unexpected format.",
        errorRefresh: "Please refresh the page to try again.",

        // Loading
        loadingText: "Searching for the wind...",
        loadingSpotData: "Loading spot data...",
        loadingForecast: "Waiting for forecast data...",
        forecastTimeout: "Connection timed out while waiting for forecast data. Please try again later.",

        // Favorites
        noFavoritesTitle: "No Favorites Yet",
        noFavoritesDescription: "Click the star icon on any spot card to add it to your favorites.",
        addToFavorites: "Add to favorites",
        removeFromFavorites: "Remove from favorites",

        // Modals
        aiAnalysisTitle: "AI Analysis",
        spotInformationTitle: "Spot Information",
        icmForecastTitle: "ICM Forecast",
        aiDisclaimer: "⚠️ This data is generated by AI and may contain errors or invalid information!",
        appInfoModalTitle: "About VARUN.SURF",
        appInfoDescription: "VARUN.SURF aggregates weather forecasts and live wind conditions for kitesurfers worldwide. The goal of the project is promotion of the watersports and physical activities, as well as encouraging to discover new places.",
        appInfoContactTitle: "Contact",
        appInfoContactText: "Questions or ideas? Email <a href=\"mailto:piotr@varun.surf\" class=\"modal-link\">piotr@varun.surf</a>.",
        appInfoNewSpotTitle: "Suggest a new kite spot",
        appInfoNewSpotText: "If you want to suggest a new kite spot, <a href=\"https://pwittchen.notion.site/28a649d2871780368191c6ce5a64029e\" class=\"modal-link\" target=\"_blank\" rel=\"noopener\">fill in the form</a>.",
        appInfoCollaborationTitle: "Collaboration",
        appInfoCollaborationText: "I welcome collaboration! Open an issue or PR in <a href=\"https://github.com/pwittchen/varun.surf\" class=\"modal-link\" target=\"_blank\" rel=\"noopener\">GitHub repository</a> or reach out via email. If you would like to advertise your service related to the kitesurfing or other water sports (e.g. shop, kite school, travels, insurance, etc.) on this website, please contact me.",

        // Spot info labels
        overviewLabel: "Overview",
        spotTypeLabel: "Spot Type",
        bestWindLabel: "Best Wind",
        waterTempLabel: "Water Temperature",
        experienceLabel: "Experience Level",
        launchTypeLabel: "Launch Type",
        hazardsLabel: "Hazards",
        seasonLabel: "Season",

        // Kite size calculator
        kiteSizeCalculatorTitle: "Kite & Board Size Calculator",
        windSpeedLabel: "Wind Speed (knots)",
        windSpeedPlaceholder: "Enter wind speed in knots",
        riderWeightLabel: "Rider Weight (kg)",
        riderWeightPlaceholder: "Enter your weight in kg",
        skillLevelLabel: "Skill Level & Conditions",
        skillLevelPlaceholder: "Select skill level & conditions",
        skillBeginnerFlat: "Beginner - Flat Water",
        skillBeginnerSmall: "Beginner - Small Waves",
        skillIntermediateFlat: "Intermediate - Flat Water",
        skillIntermediateMedium: "Intermediate - Medium Waves",
        skillAdvancedFlat: "Advanced - Flat Water",
        skillAdvancedMedium: "Advanced - Medium Waves",
        skillAdvancedLarge: "Advanced - Large Waves",
        calculateButton: "Calculate",
        recommendedEquipment: "Recommended Equipment",
        kiteSizeLabel: "Kite Size",
        boardSizeLabel: "Board Size",
        calcDisclaimer: "⚠️ These are general recommendations. Actual equipment choice may vary based on specific kite model, board type, and personal preference. Always consult with experienced riders or instructors for your local conditions.",

        // Calculator warnings
        warningInvalidWindSpeed: "⚠️ <strong>INVALID WIND SPEED</strong><br><br>Please enter a valid wind speed between 5 and 50 knots.",
        warningInvalidWeight: "⚠️ <strong>INVALID RIDER WEIGHT</strong><br><br>Please enter a valid rider weight between 40 and 150 kg.",
        warningWeightTooLow: "⚠️ <strong>WEIGHT TOO LOW</strong><br><br>Your weight is too low and riding may be dangerous. Kitesurfing requires sufficient body weight for control and safety.",
        warningSkillLevelRequired: "⚠️ <strong>SKILL LEVEL REQUIRED</strong><br><br>Please select your skill level and conditions.",
        warningWeightTooHigh: "😉 Maybe you should lose some weight before going onto the water!",
        warningExtremeWind: "⚠️ <strong>EXTREME CONDITIONS!</strong><br><br>Wind speeds above 40 knots are extremely dangerous. We strongly recommend NOT going onto the water in these conditions. Stay safe!",
        warningLowWind: "💨 <strong>LOW WIND CONDITIONS</strong><br><br>There is not enough wind for riding with a regular setup. However, you could try going on a <strong>kite foil board</strong>, which works great in light wind conditions!",
        warningInsufficientWindWaves: "🌊 <strong>INSUFFICIENT WIND FOR WAVE CONDITIONS</strong><br><br>Wind speed below 15 knots is not enough for riding in medium or large waves. Waves create additional resistance and you need more wind power to maintain speed and control. We recommend NOT going onto the water in these conditions.",

        // Countries
        Poland: "Poland",
        Czechia: "Czechia",
        Austria: "Austria",
        Belgium: "Belgium",
        Switzerland: "Switzerland",
        Latvia: "Latvia",
        Lithuania: "Lithuania",
        Estonia: "Estonia",
        Denmark: "Denmark",
        Sweden: "Sweden",
        Norway: "Norway",
        Iceland: "Iceland",
        Spain: "Spain",
        Portugal: "Portugal",
        Italy: "Italy",
        Greece: "Greece",
        France: "France",
        Germany: "Germany",
        Netherlands: "Netherlands",
        Croatia: "Croatia",
        Ireland: "Ireland",
        UK: "UK",
        Turkey: "Turkey",
        Morocco: "Morocco",
        Egypt: "Egypt",
        CapeVerde: "Cape Verde",
        Mauritius: "Mauritius",
        Brazil: "Brazil",
        Peru: "Peru",
        Chile: "Chile",
        USA: "USA"
    },
    pl: {
        // Page title
        pageTitle: "VARUN.SURF",

        // Header
        searchPlaceholder: "Szukaj spotów...",
        allCountries: "Wszystkie",
        spotsCount: "spotów",

        // Tooltips
        themeToggleTooltip: "Przełącz motyw",
        favoritesToggleTooltip: "Zobacz ulubione",
        infoToggleTooltip: "Informacje o aplikacji",
        infoButtonLabel: "Informacje",
        kiteSizeToggleTooltip: "Kalkulator rozmiaru latawca i deski",
        columnToggleTooltip: "Przełącz 2/3 kolumny",
        languageToggleTooltip: "Zmień język",

        // Weather table headers
        dateHeader: "Data",
        windHeader: "Wiatr",
        gustsHeader: "Szkwały",
        directionHeader: "Kierunek",
        tempHeader: "Temp",
        rainHeader: "Deszcz",
        waveHeader: "Fala",
        nowLabel: "TERAZ",

        // Footer
        footerDisclaimer: "prognoza pogody i warunki wiatrowe w czasie rzeczywistym dla kitesurferów",

        // Days of week (short forms as they appear in forecast)
        dayToday: "Dzisiaj",
        dayTomorrow: "Jutro",
        dayDay3: "Dzień 3",
        dayDay4: "Dzień 4",
        dayDay5: "Dzień 5",

        // Language code
        langCode: "PL",

        // Error handling
        error: "Błąd",
        invalidSpotId: "Nieprawidłowy lub brakujący identyfikator spotu.",
        spotNotFound: "Nie znaleziono tego spotu. Sprawdź link lub wybierz inny spot.",
        errorLoadingSpot: "Nie można załadować informacji o spocie. Spróbuj ponownie za chwilę.",

        // Error messages
        errorNoSpotsTitle: "Nie znaleziono spotów",
        errorNoSpotsDescription: "Nie znaleziono spotów kitesurfingowych dla wybranego filtra.",
        errorNoSpotsSearchDescription: "Nie znaleziono spotów pasujących do",
        errorTryAdjusting: "Spróbuj dostosować wyszukiwanie lub wybrać \"Wszystkie\" kraje.",
        errorLoadDataTitle: "Nie udało się załadować danych pogodowych",
        errorLoadDataDescription: "Nie można pobrać najnowszych informacji pogodowych z serwera.",
        errorDataNotFoundTitle: "Nie znaleziono źródła danych",
        errorDataNotFoundDescription: "Endpoint z danymi pogodowymi jest niedostępny. Sprawdź, czy serwer działa.",
        errorServerTitle: "Błąd serwera",
        errorServerDescription: "Usługa pogodowa ma trudności techniczne. Spróbuj ponownie później.",
        errorConnectionTitle: "Błąd połączenia",
        errorConnectionDescription: "Nie można połączyć się z usługą pogodową. Sprawdź połączenie internetowe i upewnij się, że serwer działa.",
        errorDataFormatTitle: "Błąd formatu danych",
        errorDataFormatDescription: "Otrzymane dane pogodowe są uszkodzone lub w nieoczekiwanym formacie.",
        errorRefresh: "Odśwież stronę, aby spróbować ponownie.",

        // Loading
        loadingText: "Szukam wiatru...",
        loadingSpotData: "Ładowanie danych spotu...",
        loadingForecast: "Oczekiwanie na dane prognozy...",
        forecastTimeout: "Przekroczono czas oczekiwania na dane prognozy. Spróbuj ponownie później.",

        // Favorites
        noFavoritesTitle: "Brak ulubionych",
        noFavoritesDescription: "Kliknij ikonę gwiazdki na karcie spotu, aby dodać go do ulubionych.",
        addToFavorites: "Dodaj do ulubionych",
        removeFromFavorites: "Usuń z ulubionych",

        // Modals
        aiAnalysisTitle: "Analiza AI",
        spotInformationTitle: "Informacje o spocie",
        icmForecastTitle: "Prognoza ICM",
        aiDisclaimer: "⚠️ Te dane są generowane przez AI i mogą zawierać błędy lub nieprawidłowe informacje!",
        appInfoModalTitle: "O VARUN.SURF",
        appInfoDescription: "VARUN.SURF prezentuje prognozy pogody i aktualne warunki wiatrowe dla kitesurferów na całym świecie. Celem projektu jest promocja sportów wodnych i aktywności fizycznej oraz zachęcanie do odkrywania nowych miejsc.",
        appInfoContactTitle: "Kontakt",
        appInfoContactText: "Masz pytania lub pomysły? Napisz na <a href=\"mailto:piotr@varun.surf\" class=\"modal-link\">piotr@varun.surf</a>.",
        appInfoNewSpotTitle: "Zaproponuj nowy kite spot",
        appInfoNewSpotText: "Jeśli chcesz zaproponować nowy kite spot, <a href=\"https://pwittchen.notion.site/28a649d2871780368191c6ce5a64029e\" class=\"modal-link\" target=\"_blank\" rel=\"noopener\">wypełnij formularz</a>.",
        appInfoCollaborationTitle: "Współpraca",
        appInfoCollaborationText: "Chcesz współtworzyć projekt lub udostępnić nowe źródła danych? Otwórz zgłoszenie albo pull request w <a href=\"https://github.com/pwittchen/varun.surf\" class=\"modal-link\" target=\"_blank\" rel=\"noopener\">repozytorium GitHub</a> lub napisz maila. Jeżeli chciałbyś zareklamować swoje usługi związane z kitesurfingiem lub innymi sportami wodnymi (np. sklep, szkółkę, wyjazdy, ubezpieczenia, itd.) na tej stronie, proszę o kontakt.",

        // Spot info labels
        overviewLabel: "Przegląd",
        spotTypeLabel: "Typ spotu",
        bestWindLabel: "Najlepszy wiatr",
        waterTempLabel: "Temperatura wody",
        experienceLabel: "Poziom doświadczenia",
        launchTypeLabel: "Typ startu",
        hazardsLabel: "Zagrożenia",
        seasonLabel: "Sezon",

        // Kite size calculator
        kiteSizeCalculatorTitle: "Kalkulator rozmiaru latawca i deski",
        windSpeedLabel: "Prędkość wiatru (węzły)",
        windSpeedPlaceholder: "Wprowadź prędkość wiatru w węzłach",
        riderWeightLabel: "Waga ridera (kg)",
        riderWeightPlaceholder: "Wprowadź swoją wagę w kg",
        skillLevelLabel: "Poziom umiejętności i warunki",
        skillLevelPlaceholder: "Wybierz poziom umiejętności i warunki",
        skillBeginnerFlat: "Początkujący - Płaska woda",
        skillBeginnerSmall: "Początkujący - Małe fale",
        skillIntermediateFlat: "Średniozaawansowany - Płaska woda",
        skillIntermediateMedium: "Średniozaawansowany - Średnie fale",
        skillAdvancedFlat: "Zaawansowany - Płaska woda",
        skillAdvancedMedium: "Zaawansowany - Średnie fale",
        skillAdvancedLarge: "Zaawansowany - Duże fale",
        calculateButton: "Oblicz",
        recommendedEquipment: "Zalecany sprzęt",
        kiteSizeLabel: "Rozmiar latawca",
        boardSizeLabel: "Rozmiar deski",
        calcDisclaimer: "⚠️ To są ogólne zalecenia. Rzeczywisty wybór sprzętu może się różnić w zależności od konkretnego modelu latawca, typu deski i osobistych preferencji. Zawsze konsultuj się z doświadczonymi riderami lub instruktorami dla swoich lokalnych warunków.",

        // Calculator warnings
        warningInvalidWindSpeed: "⚠️ <strong>NIEPRAWIDŁOWA PRĘDKOŚĆ WIATRU</strong><br><br>Wprowadź prawidłową prędkość wiatru między 5 a 50 węzłów.",
        warningInvalidWeight: "⚠️ <strong>NIEPRAWIDŁOWA WAGA RIDERA</strong><br><br>Wprowadź prawidłową wagę między 40 a 150 kg.",
        warningWeightTooLow: "⚠️ <strong>WAGA ZBYT NISKA</strong><br><br>Twoja waga jest zbyt niska i jazda może być niebezpieczna. Kitesurfing wymaga odpowiedniej wagi ciała dla kontroli i bezpieczeństwa.",
        warningSkillLevelRequired: "⚠️ <strong>WYMAGANY POZIOM UMIEJĘTNOŚCI</strong><br><br>Wybierz swój poziom umiejętności i warunki.",
        warningWeightTooHigh: "😉 Może powinieneś schudnąć przed wyjściem na wodę!",
        warningExtremeWind: "⚠️ <strong>EKSTREMALNE WARUNKI!</strong><br><br>Prędkość wiatru powyżej 40 węzłów jest bardzo niebezpieczna. Zdecydowanie odradzamy wychodzenie na wodę w takich warunkach. Bądź bezpieczny!",
        warningLowWind: "💨 <strong>SŁABE WARUNKI WIATROWE</strong><br><br>Nie ma wystarczającego wiatru do jazdy ze standardowym setupem. Możesz jednak spróbować <strong>deski foilowej</strong>, która świetnie sprawdza się w słabym wietrze!",
        warningInsufficientWindWaves: "🌊 <strong>NIEWYSTARCZAJĄCY WIATR DLA WARUNKÓW FALOWYCH</strong><br><br>Prędkość wiatru poniżej 15 węzłów jest niewystarczająca do jazdy na średnich lub dużych falach. Fale tworzą dodatkowy opór i potrzebujesz więcej mocy wiatru, aby utrzymać prędkość i kontrolę. Nie zalecamy wychodzenia na wodę w takich warunkach.",

        // Countries
        Poland: "Polska",
        Czechia: "Czechy",
        Austria: "Austria",
        Belgium: "Belgia",
        Switzerland: "Szwajcaria",
        Latvia: "Łotwa",
        Lithuania: "Litwa",
        Estonia: "Estonia",
        Denmark: "Dania",
        Sweden: "Szwecja",
        Norway: "Norwegia",
        Iceland: "Islandia",
        Spain: "Hiszpania",
        Portugal: "Portugalia",
        Italy: "Włochy",
        Greece: "Grecja",
        France: "Francja",
        Germany: "Niemcy",
        Netherlands: "Holandia",
        Croatia: "Chorwacja",
        Ireland: "Irlandia",
        UK: "Anglia",
        Turkey: "Turcja",
        Morocco: "Maroko",
        Egypt: "Egipt",
        CapeVerde: "Cabo Verde",
        Mauritius: "Mauritius",
        Brazil: "Brazylia",
        Peru: "Peru",
        Chile: "Chile",
        USA: "USA"
    }
};

// Get translation for current language
function t(key) {
    const currentLang = localStorage.getItem('language') || 'en';
    return translations[currentLang][key] || translations.en[key] || key;
}
